name: Ask ChatGPT

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  respond:
    if: startsWith(github.event.comment.body, '/ask ')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Call OpenAI API
        id: ask
        run: |
          REQUEST=$(echo "${{ github.event.comment.body }}" | sed 's/^\/ask //')
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -sS \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4o",
              "messages": [
                { "role": "system", "content": "You are a code generator. Only output Git diffs. Always wrap them in triple backticks and diff tags." },
                { "role": "user", "content": "'"$REQUEST"'" }
              ]
            }' | jq -r '.choices[0].message.content')
          
          echo "$RESPONSE" > patch.diff
          echo "::set-output name=response::$RESPONSE"

      - name: Apply patch
        run: git apply patch.diff || echo "No changes to apply"

      - name: Commit & Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ask-${{ github.event.issue.number }}
          git add .
          git commit -m "feat: ${{ github.event.comment.body }}" || echo "Nothing to commit"
          git push -u origin HEAD || echo "Nothing to push"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "feat: ${{ github.event.comment.body }}"
          title: "feat: ${{ github.event.comment.body }}"
          body: |
            This PR was auto-generated by ChatGPT in response to your /ask comment.
          base: main
