name: Ask ChatGPT

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  respond:
    if: startsWith(github.event.comment.body, '/ask ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Call OpenAI for diff
        id: openai
        uses: m4bzie/openai-api-action@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model: gpt-4o-mini
          prompt: |
            You are a code generator.  Given this repository and the user’s request,
            produce a Git diff *only*, with no explanations.  ALWAYS wrap your
            diff between lines that start with “```diff” and end with “```”.
            Request: ${{ github.event.comment.body }}

      - name: Apply patch
        run: |
          echo "${{ steps.openai.outputs.result }}" > patch.diff
          git apply patch.diff

      - name: Commit & push branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b ask-${{ github.event.issue.number }}
          git add .
          git commit -m "feat: ${{ github.event.comment.body }}"
          git push -u origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "feat: ${{ github.event.comment.body }}"
          title: "feat: ${{ github.event.comment.body }}"
          body: |
            This PR was auto‑generated by ChatGPT in response to your `/ask` comment.
          base: main
          head: ask-${{ github.event.issue.number }}
